import { type CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'https://inctagram.work/api/v1/graphql',
  // This assumes that all your source files are in a top-level `src/` directory - you might need to adjust this to your file structure
  documents: ['./**/*.{ts,tsx}'],
  // Don't exit with non-zero status when there are no documents
  ignoreNoDocuments: true,
  watch: ['./**'],
  generates: {
    './generated/graphql.ts': {
      plugins: ['typescript'],
    },
    './': {
      preset: 'near-operation-file',
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        extension: '.generated.ts',
        baseTypesPath: '/generated/graphql.ts',
      },
      plugins: ['typescript-operations'],
      // Note: these config options moved from the other generated file config
      config: {
        avoidOptionals: {
          // Use `null` for nullable fields instead of optionals
          field: true,
          // Allow nullable input fields to remain unspecified
          inputValue: false,
        },
        // Use `unknown` instead of `any` for unconfigured scalars
        defaultScalarType: 'unknown',
        scalars: {
          DateTime: 'string',
          Date: 'string',
          Time: 'string',
          JSON: 'Record',
          JSONObject: 'Record',
          Upload: 'File',
          BigInt: 'bigint',
          UUID: 'string',
        },
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
      },
    },
  },
};

export default config;
