import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { Header } from "widgets/header/ui/Header";

import { AppProviders } from "./provider";

import "@/shared/styles/globals.scss";

import "@dangerous-tigers/framehub-ui-kit/components/styles";

export const metadata: Metadata = {
  title: "Framehub-Admin",
  description: "Generated by create next app",
};

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <Header />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
