import type { Metadata } from "next";
import { getLocale, getMessages } from "next-intl/server";
import type { ReactNode } from "react";

import { AppProviders } from "./provider";

import "@/shared/styles/globals.scss";

import "@dangerous-tigers/framehub-ui-kit/components/styles";

export const metadata: Metadata = {
  title: "Framehub-Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  let locale: string;
  let messages: Record<string, unknown>;

  try {
    locale = await getLocale();
    messages = await getMessages();
  } catch {
    locale = "en";
    messages = (await import("../messages/en.json")).default;
  }

  return (
    <html lang={locale}>
      <body>
        <AppProviders locale={locale} messages={messages}>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
